### PR TITLE
FIX use get_one_solution() to fix tests

### PR DESCRIPTION
**Pull request by mathurinm**

### CODE REVIEW

**Comment by mathurinm** [comment]
the tests fail because something reinstalls numpy after celer has been built, which breaks stuff

**Comment by tomMoral** [comment]
I would say rerun the CI, this is probably due to a spurious update of one package concurrent to the CI run.
If it fails again, we can look into why.

**Comment by tomMoral** [comment]
that's not it... then this means that one package has been updated and now requires a pinned version of `numpy`, that changes the one used to compile `celer`.
Can you reproduce locally? If so, it would be nice to run the test iteratively, adding the other solvers one at the time to identify the culprit.

**Comment by jolars** [comment]
I'm merging this anyway because the changes are necessary anyway. I opened a separate issue regarding the tests here: https://github.com/jolars/benchmark_lasso_path/issues/6

**Pull request merged**
