### PR TITLE
WIP add LARS solver

### PR DESCRIPTION
**Pull request by cassiofragadantas**
Main issues/challenges to be discussed:
1. stopping strategy: *n_iter* does not have the same meaning as for other iterative solvers. The LARS parameter *max_iter* refers to the number of nodes/breakpoints in the path to be computed. Therefore, setting *max_iter* to a small value actually implies that LARS won't compute the entire path (until *min_alpha*) but will rather stop prematurely. Regardless, I just kept the stopping strategy based on the number of iterations for now and it does lead to nice-looking convergence curves.
2. returning coefficients for values of alpha in the grid: LARS does not return the coefficients on a predefined grid, but instead at the values of alpha corresponding to the nodes/breakpoints in the path. The coefficients at any given value of alpha can be computed via linear interpolation. For now, this is done in a (probably) sub-optimal way. To be improved eventually.

### CODE REVIEW

**Comment by jolars** [comment]
Thank you for this, nice work!

> Main issues/challenges to be discussed:
> 
> 1. stopping strategy: _n_iter_ does not have the same meaning as for other iterative solvers. The LARS parameter _max_iter_ refers to the number of nodes/breakpoints in the path to be computed. Therefore, setting _max_iter_ to a small value actually implies that LARS won't compute the entire path (until _min_alpha_) but will rather stop prematurely. Regardless, I just kept the stopping strategy based on the number of iterations for now and it does lead to nice-looking convergence curves.

I think that the LARS solver should just solve the complete path to machine precision, i.e. not changing or setting `max_iter` to the maximum possible value. It's obviously not a fair situation for LARS, but the way the benchmark is setup right now I think that's the only possible way to do it. Maybe there's room for a separate lasso_homotopy benchmark that could compare different algorithms for the exact lasso path instead. 

> 2. returning coefficients for values of alpha in the grid: LARS does not return the coefficients on a predefined grid, but instead at the values of alpha corresponding to the nodes/breakpoints in the path. The coefficients at any given value of alpha can be computed via linear interpolation. For now, this is done in a (probably) sub-optimal way. To be improved eventually.

If you wanted, you could instead just use the lars implementation in R (https://cran.r-project.org/web/packages/lars/index.html), which has a predict() method that does the work for you.

**Comment by cassiofragadantas** [comment]
> Thank you for this, nice work!
> 
> > Main issues/challenges to be discussed:
> > 
> > 1. stopping strategy: _n_iter_ does not have the same meaning as for other iterative solvers. The LARS parameter _max_iter_ refers to the number of nodes/breakpoints in the path to be computed. Therefore, setting _max_iter_ to a small value actually implies that LARS won't compute the entire path (until _min_alpha_) but will rather stop prematurely. Regardless, I just kept the stopping strategy based on the number of iterations for now and it does lead to nice-looking convergence curves.
> 
> I think that the LARS solver should just solve the complete path to machine precision, i.e. not changing or setting `max_iter` to the maximum possible value. It's obviously not a fair situation for LARS, but the way the benchmark is setup right now I think that's the only possible way to do it. Maybe there's room for a separate lasso_homotopy benchmark that could compare different algorithms for the exact lasso path instead.

I agree that it makes more sense to set `max_iter` to infinity and let LARS compute the full path. The only downside is that we wouldn't really have a convergence vs. time curve, only one final point. It is either that (i.e, no curve) or as currently implemented (i.e, a kind of "fake" curve where the initial points don't fully make sense).
> 
> > 2. returning coefficients for values of alpha in the grid: LARS does not return the coefficients on a predefined grid, but instead at the values of alpha corresponding to the nodes/breakpoints in the path. The coefficients at any given value of alpha can be computed via linear interpolation. For now, this is done in a (probably) sub-optimal way. To be improved eventually.
> 
> If you wanted, you could instead just use the lars implementation in R (https://cran.r-project.org/web/packages/lars/index.html), which has a predict() method that does the work for you.

Thanks for the ref. It would indeed lead to a much cleaner code. I will take a look.
Or maybe should we have two separate LARS (lars-sklearn and lars-R) for a comparison? Not sure this is relevant.

**Comment by jolars** [comment]
>  I agree that it makes more sense to set max_iter to infinity and let LARS compute the full path. The only downside is that we wouldn't really have a convergence vs. time curve, only one final point. It is either that (i.e, no curve) or as currently implemented (i.e, a kind of "fake" curve where the initial points don't fully make sense).

Yeah, I know, but I think it still might be the best option here.

> Or maybe should we have two separate LARS (lars-sklearn and lars-R) for a comparison? Not sure this is relevant.

I guess it depends on how different the implementations really are, which I don't really know about. If they're very similar it will probably just be a R+Fortran vs Cython comparison, which I guess is somewhat interesting but probably not worth prioritizing.

**Comment by jolars** [comment]
I've added support for fitting the intercept now, and it seems to work fine:

image

**Comment by jolars** [comment]
I'm merging this into the repo now, thanks for all the work @cassiofragadantas!

**Pull request merged**
